# Generated by Django 6.0.3 on 2026-04-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('total_frames', models.IntegerField()),
                ('average_activity', models.FloatField()),
                ('max_activity', models.FloatField()),
                ('max_time', models.FloatField()),
                ('min_activity', models.FloatField()),
                ('peak_start', models.FloatField()),
                ('peak_end', models.FloatField()),
                ('total_integral', models.FloatField()),
                ('method', models.CharField(default='Riemann Sum', max_length=50)),
                ('canvas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='canvas.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='canvas.canvas')),
            ],
        ),
    ]
