# Generated by Django 6.0.3 on 2026-04-05 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kanvas Baru', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('object_count', models.IntegerField(blank=True, null=True)),
                ('motion_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='canvas.canvas')),
            ],
            options={
                'ordering': ['frame_index'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('max_object', models.IntegerField(blank=True, null=True)),
                ('avg_motion', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='canvas.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='canvas.canvas')),
            ],
        ),
    ]
