# Generated by Django 4.2.29 on 2026-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='roi_x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvas',
            name='roi_x2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvas',
            name='roi_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvas',
            name='roi_y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
