# Generated by Django 4.2.29 on 2026-04-14 05:25

import canvas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_canvas_roi_x1_canvas_roi_x2_canvas_roi_y1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=canvas.models.random_thumbnails_filename),
        ),
    ]
