# Generated by Django 4.2.29 on 2026-04-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_analysisresult_graph_data_analysisresult_heatmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
